version: "3.7"
services:
  whiskerboard:
    image: rickpeters/whiskerboard
    ports:
      - "8000:8000"
      - "8080:8080"
    links:
      - postgres
      - redis
    command: /usr/local/bin/supervisord -c /usr/src/python/whiskerboard/config/supervisor.conf
    volumes:
      - ./whiskerboard/logs:/whiskerboard/logs
      - ./images/:/usr/src/python/whiskerboard/board/static/images
      - ./templates:/usr/src/python/whiskerboard/board/templates
      - ./css:/usr/src/python/whiskerboard/board/static/css
      - ./config:/usr/src/python/whiskerboard/config
  postgres:
    image: postgres:9.3
    volumes:
      - ./pgdata/data:/data
      - ./pgdata/log:/var/log/postgresql
  redis:
    image: redis:2.8
    command: redis-server
    volumes:
      - ./redis:/data