version: "3.7"
services:
  whiskerboard:
    image: agaveapi/whiskerboard
    ports:
      - "8000:8000"
      - "8080:8080"
    links:
      - postgres
      - redis
    volumes:
      - ./whiskerboard/logs:/whiskerboard/logs
      - ./images:/usr/src/python/whiskerboard/static/images
      - ./templates:/usr/src/python/whiskerboard/templates
      - ./css:/usr/src/python/whiskerboard/static/css
  postgres:
    image: postgres:9.3
    volumes:
      - ./pgdata/data:/data
      - ./pgdata/log:/var/log/postgresql
  redis:
    image: redis:2.8
    command: redis-server
    volumes:
      - ./redis:/data