version: "3.7"
services:
  redis:
    image: redis:2.8
    volumes:
      - ./redis:/data
    command: redis-server --appendonly yes
  postgres:
    image: postgres:9.3
    volumes:
      - ./pgdata/data:/data
      - ./pgdata/log:/var/log/postgresql
  stashboard:
    image: agaveapi/whiskerboard
#   command: ./manage.py runserver
    links:
    - postgres
    - redis
    ports:
    - "8000:8000"
    - "10023:22"
    volumes:
      - ./whiskerboard/logs:/whiskerboard/logs
      - ./images:/usr/src/python/whiskerboard/static/images/
      - ./templates:/usr/src/python/whiskerboard/templates
      - ./css:/usr/src/python/whiskerboard/static/css

      ##
       #  ./manage.py collectstatic --noinput
    # ./manage.py syncdb --noinput
    #  ./manage.py migrat
    #  ./manage.py migrate
   #  ./manage.py migrate --noinput